version: '3'

services:
  php:
    container_name: setup-php-eTarefas
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./e-Tarefas_app:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - '9003:9000'
    expose:
      - '9003'
    networks:
      - setup-network

  nginx:
    container_name: setup-nginx-eTarefas
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8484:80'
      - '4444:443'
    volumes:
      - ./e-Tarefas_app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-network

  mysql:
    container_name: setup-mysql-eTarefas
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-network
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: e-tarefas_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: setup-phpmyadmin-eTarefas
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8889:80'
    networks:
      - setup-network
    environment:
      PMA_HOST: setup-mysql-eTarefas
    depends_on:
      - mysql

  redis:
    container_name: setup-redis-eTarefas
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6381:6379'

networks:
  setup-network:
    driver: bridge


volumes:
  setup-data:
    driver: local
